-- vim.cmd.colorscheme("default")
-- vim.api.nvim_set_hl(0, "Normal", { bg = "none"})
-- vim.api.nvim_set_hl(0, "NormalFloat", { bg = "none"})
-- vim.api.nvim_set_hl(0, "PMenu", { bg = "none"})

-- torte
-- koehler
-- rose-pine
-- elflord
-- murphy
-- quiet
-- retrobox
-- vim
-- default
